# For local development only.

version: '3'

services:
  cphalcon-7.4:
    container_name: cphalcon-7.4
    hostname: cphalcon-74
    build: docker/7.4
    working_dir: /srv
    volumes:
      - .:/srv

  cphalcon-8.0:
    container_name: cphalcon-8.0
    hostname: cphalcon-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

  mysql:
    container_name: cphalcon-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret

  postgres:
    container_name: cphalcon-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon

  redis:
    container_name: cphalcon-redis
    image: redis:5-alpine

  memcached:
    container_name: cphalcon-memcached
    image: memcached:1.5-alpine
