phalcon:
  baseuri: /phalcon/
models:
  metadata: memory
database:
  adapter: mysql
  host: localhost
  username: user
  password: passwd
  name: demo
test:
  parent:
    property: 1
    property2: yeah
