name: Cleanup Packagecloud packages

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00

jobs:
  # To prevent build a particular commit use
  #     git commit -m "......... [ci skip]"
  if: "!contains(github.event.head_commit.message, 'ci skip')"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Cleanup Packagecloud
        run: php .ci/cleanup-packages.php
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
